# Makefile generated by gb: http://go-gb.googlecode.com
# gb provides configuration-free building and distributing

include $(GOROOT)/src/Make.inc

TARG=Normalize-URL
GOFILES=\
	normalize.go\

# gb: this is the local install
GBROOT=.

# gb: compile/link against local install
GC+= -I $(GBROOT)/_obj
LD+= -L $(GBROOT)/_obj
# gb: compile/link against GOPATH entries
GC+= -I /Users/bjorn/apps/go/pkg/$(GOOS)_$(GOARCH)
LD+= -L /Users/bjorn/apps/go/pkg/$(GOOS)_$(GOARCH)

package: $(GBROOT)/_obj/$(TARG).a

include $(GOROOT)/src/Make.pkg
